name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log Setting up nodejs
        run: echo "Setting up nodejs environment for testing..."
      - name: Set up nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: log Installing dependencies
        run: echo "Installing dependencies..."
      - name: Install dependencies
        run: npm install

      - name: log Running tests
        run: echo "Running tests..."
      - name: Run tests
        run: npm run test
    if: github.event_name == 'pull_request'

  build:
    name: Build Project
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: log Setting up nodejs
        run: echo "Setting up nodejs environment for building..."
      - name: Set up nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: log Installing dependencies
        run: echo "Installing dependencies..."
      - name: Install dependencies
        run: npm install

      - name: log Building project
        run: echo "Building the project..."
      - name: Build project
        run: npm run build